from dataclasses import dataclass, field
from typing import Dict, Tuple


@dataclass(frozen=True)
class Settings:
  websocket_path: str = "/ws"
  max_frame_width: int = 1920
  websocket_frame_queue_size: int = 1
  include_metrics: bool = True
  include_risk_breakdown: bool = True
  fps_window: int = 30

  calibration_enabled: bool = True
  calibration_stage_neutral_min_sec: float = 15.0
  calibration_stage_neutral_max_sec: float = 28.0
  calibration_stage_gaze_min_sec: float = 15.0
  calibration_stage_gaze_max_sec: float = 30.0
  calibration_stage_gaze_target_min_sec: float = 3.5
  calibration_stage_gaze_target_max_sec: float = 7.0
  calibration_stage_head_min_sec: float = 15.0
  calibration_stage_head_max_sec: float = 30.0
  calibration_stage_hand_min_sec: float = 12.0
  calibration_stage_hand_max_sec: float = 24.0
  calibration_total_max_sec: float = 140.0
  calibration_completed_hold_sec: float = 3.5
  calibration_min_face_frames: int = 75
  calibration_neutral_target_frames: int = 120
  calibration_gaze_min_samples: int = 36
  calibration_gaze_target_frames: int = 18
  calibration_gaze_target_visible_ratio: float = 0.60
  calibration_gaze_boundary_scale: float = 0.68
  calibration_gaze_min_side_frames: int = 8
  calibration_gaze_min_transitions: int = 4
  calibration_gaze_min_signal_amplitude: float = 0.055
  calibration_gaze_signal_sign_threshold: float = 0.030
  calibration_gaze_min_eye_visible_ratio: float = 0.50
  calibration_head_min_samples: int = 36
  calibration_head_min_direction_frames: int = 6
  calibration_head_min_range_deg: float = 8.0
  calibration_pitch_ratio_min_range: float = 0.018
  calibration_pitch_ratio_boundary_scale: float = 0.62
  calibration_hand_min_samples: int = 24
  calibration_hand_min_positive_frames: int = 3
  calibration_background_motion_enabled: bool = True
  calibration_background_motion_grid_w: int = 48
  calibration_background_motion_grid_h: int = 27
  calibration_background_motion_diff_threshold: float = 18.0
  calibration_background_motion_max_global_ratio: float = 0.38
  calibration_background_motion_cell_activity_threshold: float = 0.18
  calibration_background_motion_min_zone_cells: int = 8
  calibration_background_motion_max_zones: int = 8
  calibration_background_motion_face_exclude_ratio: float = 0.35

  max_faces: int = 5
  tracker_max_disappeared: int = 15
  tracker_distance_threshold: float = 90.0
  tracker_merge_iou: float = 0.45
  tracker_embedding_similarity_threshold: float = 0.60
  high_movement_threshold: float = 0.045
  vertical_head_pitch_threshold: float = 18.0
  vertical_head_pitch_enter_threshold: float = 17.0
  vertical_head_pitch_exit_threshold: float = 10.0
  vertical_head_activation_frames: float = 5.0
  vertical_head_pitch_ema_alpha: float = 0.35
  vertical_head_pitch_baseline_alpha: float = 0.05
  vertical_head_pitch_active_baseline_alpha: float = 0.02
  vertical_head_pitch_ratio_dead_zone: float = 0.04
  vertical_pitch_ratio_up_threshold: float = 0.48
  vertical_pitch_ratio_down_threshold: float = 0.62
  vertical_head_low_visibility_persist_sec: float = 1.2
  vertical_head_pitch_velocity_gate: float = 0.9
  vertical_head_baseline_movement_threshold: float = 0.025
  vertical_head_activation_movement_threshold: float = 0.016
  vertical_head_baseline_yaw_threshold: float = 14.0
  vertical_head_span_window_frames: float = 6.0
  vertical_head_pitch_span_gate: float = 4.6
  vertical_head_delta_velocity_gate: float = 0.52
  vertical_head_y_velocity_gate: float = 0.018
  vertical_head_y_span_gate: float = 0.075
  vertical_head_large_movement_gate: float = 0.018

  yolo_model_path: str = "yolov8n.pt"
  yolo_confidence: float = 0.24
  yolo_iou: float = 0.40
  yolo_inference_fps: float = 8.0
  person_detector_inference_fps: float = 6.0
  person_min_confidence: float = 0.30
  person_confirmation_min_confidence: float = 0.65
  person_min_height_width_ratio: float = 1.20
  person_max_height_width_ratio: float = 4.00
  person_min_frame_height_ratio: float = 0.18
  person_min_motion_ratio: float = 0.020
  person_confirmation_frames: int = 8
  person_face_confirmation_frames: int = 3
  person_face_anchor_grace_frames: int = 8
  person_face_anchor_ttl_frames: int = 3
  person_confirmation_hold_frames: int = 4
  person_recent_face_ttl_frames: int = 8
  person_face_top_ratio_max: float = 0.35
  person_face_anchor_top_ratio_max: float = 0.35
  person_face_center_offset_ratio_max: float = 0.36
  person_face_nose_eye_ratio_min: float = 0.20
  person_face_nose_eye_ratio_max: float = 0.60
  person_motion_variance_max: float = 1.20
  person_optical_flow_min_magnitude: float = 0.85
  person_optical_flow_max_dim: int = 160
  person_pose_min_visibility: float = 0.55
  person_shoulder_width_ratio_min: float = 0.25
  person_centroid_history_frames: int = 10
  person_centroid_drift_min_px: float = 15.0
  person_centroid_range_min_px: float = 12.0
  person_centroid_direction_min_step_px: float = 1.5
  person_centroid_direction_flip_threshold: int = 4
  person_centroid_oscillation_motion_threshold: float = 0.040
  person_periodic_motion_hz_threshold: float = 1.5
  person_periodic_motion_power_ratio_threshold: float = 0.55
  person_motion_fft_min_samples: int = 8
  person_skeleton_stability_window: int = 5
  person_skeleton_stability_min_std_px: float = 1.8
  person_skeleton_stability_motion_threshold: float = 0.035
  person_background_overlap_threshold: float = 0.38
  person_min_edge_density: float = 0.012
  person_bright_scene_mean_threshold: float = 168.0
  person_normal_scene_confirmation_confidence: float = 0.65
  person_bright_scene_confirmation_confidence: float = 0.72
  person_false_zone_overlap_threshold: float = 0.50
  person_false_zone_learning_frames: int = 4
  person_false_zone_max_count: int = 6
  person_false_zone_min_area_ratio: float = 0.010
  gadget_model_path: str = ""
  gadget_min_confidence: float = 0.35
  gadget_confirm_frames: int = 5
  gadget_roi_expand_ratio: float = 0.25
  gadget_anchor_iou: float = 0.18
  gadget_ttl_frames: int = 3
  phone_min_confidence: float = 0.38
  phone_min_area_ratio: float = 0.002
  phone_min_aspect_ratio: float = 0.12
  phone_max_aspect_ratio: float = 6.2
  phone_confirm_frames: int = 1
  person_tracker_max_disappeared: int = 10
  person_tracker_distance_threshold: float = 160.0

  scene_background_history: int = 180
  scene_background_var_threshold: float = 20.0
  scene_background_learning_rate: float = 0.004
  scene_person_mask_expand_ratio: float = 0.10
  scene_background_contour_min_area_ratio: float = 0.003
  scene_background_region_limit: int = 4

  smoothing_window: int = 15
  risk_level_thresholds: Tuple[float, float, float] = (3.0, 6.0, 9.0)
  repeated_violation_gain: float = 0.20
  repeated_violation_cap: float = 2.0
  repeated_violation_start_frames: int = 3
  exponential_smoothing_alpha: float = 0.35
  multiple_person_activation_sec: float = 1.0
  multiple_person_release_sec: float = 0.35
  multiple_faces_activation_sec: float = 0.45
  multiple_faces_release_sec: float = 0.20
  face_missing_activation_sec: float = 0.30
  face_missing_release_sec: float = 0.15
  face_not_facing_camera_activation_sec: float = 0.75
  face_not_facing_camera_release_sec: float = 0.30
  extreme_gaze_activation_sec: float = 0.55
  extreme_gaze_release_sec: float = 0.20
  vertical_head_motion_activation_sec: float = 0.40
  vertical_head_motion_release_sec: float = 0.18
  vertical_head_evidence_frames: int = 15
  vertical_head_evidence_ratio: float = 0.53
  horizontal_head_motion_activation_sec: float = 0.40
  horizontal_head_motion_release_sec: float = 0.18
  phone_detected_activation_sec: float = 0.20
  phone_detected_release_sec: float = 0.15
  attention_window_sec: float = 2.0
  attention_gaze_window_sec: float = 0.8
  attention_min_window_frames: int = 8
  attention_evidence_frames: int = 15
  attention_evidence_ratio: float = 0.53
  attention_enter_ratio: float = 0.60
  attention_transition_ratio: float = 0.35
  attention_exit_ratio: float = 0.22
  attention_micro_velocity_deg: float = 1.5
  attention_baseline_alpha: float = 0.025
  attention_sigma_multiplier: float = 3.0
  attention_noise_multiplier: float = 1.9
  attention_gaze_noise_multiplier: float = 2.2
  attention_head_weight: float = 0.7
  attention_eye_weight: float = 0.3
  attention_signal_confidence_min: float = 0.55
  attention_warning_confidence_min: float = 0.35
  attention_fast_yaw_delta_deg: float = 22.0
  attention_fast_pitch_delta_deg: float = 20.0
  attention_hard_yaw_deg: float = 45.0
  attention_hard_pitch_deg: float = 40.0
  attention_hard_gaze_offset: float = 0.65
  attention_orientation_frontalness_gate: float = 0.58
  face_orientation_eye_symmetry_threshold: float = 0.18
  gaze_extreme_horizontal_threshold: float = 0.078
  gaze_extreme_vertical_threshold: float = 0.090
  gaze_extreme_activation_frames: int = 3
  gaze_extreme_min_confidence: float = 0.08
  gaze_distance_reference_face_area_ratio: float = 0.095
  gaze_distance_scale: float = 0.28
  gaze_display_reference_diag_px: float = 2200.0
  gaze_display_scale: float = 0.18
  gaze_vertical_display_scale: float = 0.22
  gaze_face_yaw_gate: float = 18.0
  gaze_face_pitch_gate: float = 15.0
  risk_capture_threshold: float = 12.0
  risk_capture_max_images: int = 3
  risk_capture_cooldown_sec: float = 2.0
  risk_capture_jpeg_quality: int = 80
  risk_capture_enabled: bool = False
  performance_report_enabled: bool = True
  performance_report_sample_period_sec: float = 1.0
  performance_report_timeline_limit: int = 3600
  performance_report_event_limit: int = 250
  performance_report_export_dir: str = "reports"
  performance_report_auto_export_on_close: bool = True
  enable_hand_on_face_risk: bool = True
  enable_vertical_head_risk: bool = True
  enable_vertical_gaze_risk: bool = True
  enable_horizontal_head_risk: bool = True
  enable_face_orientation_risk: bool = True
  pose_landmark_stability_min: float = 0.50
  pose_smoothing_alpha: float = 0.30
  horizontal_head_activation_frames: float = 4.0
  horizontal_head_yaw_ema_alpha: float = 0.4
  horizontal_head_yaw_velocity_gate: float = 1.1
  horizontal_head_x_velocity_gate: float = 0.022
  horizontal_head_movement_gate: float = 0.010
  horizontal_head_yaw_gate: float = 8.0
  horizontal_head_exit_velocity_gate: float = 0.55
  horizontal_head_span_window_frames: float = 6.0
  horizontal_head_yaw_span_gate: float = 5.8
  horizontal_head_x_span_gate: float = 0.095
  horizontal_head_large_movement_gate: float = 0.018
  horizontal_head_large_x_span_gate: float = 0.15
  face_missing_activation_frames: int = 4
  face_missing_evasive_activation_frames: int = 2
  face_hide_motion_gate: float = 0.020
  face_hide_yaw_gate: float = 16.0
  face_hide_pitch_gate: float = 13.0
  face_orientation_ema_alpha: float = 0.35
  face_orientation_baseline_alpha: float = 0.05
  face_orientation_active_baseline_alpha: float = 0.02
  face_off_camera_yaw_gate: float = 20.0
  face_off_camera_pitch_gate: float = 16.0
  face_off_camera_yaw_exit_gate: float = 13.0
  face_off_camera_pitch_exit_gate: float = 11.0
  face_off_camera_baseline_movement_gate: float = 0.014
  face_off_camera_activation_frames: int = 10
  face_off_camera_memory_frames: int = 10

  hand_on_face_overlap_threshold: float = 0.03
  hand_on_face_bbox_expand_ratio: float = 0.15

  quality_warning_activation_frames: int = 3
  blocked_view_warning_activation_frames: int = 2
  low_light_mean_threshold: float = 58.0
  low_light_dark_ratio_threshold: float = 0.62
  dirty_camera_laplacian_threshold: float = 28.0
  dirty_camera_contrast_threshold: float = 34.0
  blocked_view_dark_ratio_threshold: float = 0.72
  blocked_view_bright_ratio_threshold: float = 0.75
  blocked_view_edge_density_threshold: float = 0.012
  blocked_view_contrast_threshold: float = 18.0
  blocked_view_center_dark_ratio_threshold: float = 0.68
  blocked_view_center_bright_ratio_threshold: float = 0.68
  blocked_view_center_edge_density_threshold: float = 0.018
  blocked_view_center_entropy_threshold: float = 4.1

  object_label_map: Dict[str, str] = field(
    default_factory=lambda: {
      "person": "person",
      "cell phone": "phone",
      "remote": "phone",
      "laptop": "phone",
      "tv": "phone",
      "mouse": "phone",
      "book": "phone",
    }
  )


settings = Settings()
